


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.util.ArrayList;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;
import org.mariuszgromada.math.mxparser.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.BorderFactory;
import javax.swing.UIManager;









/**
 *
 * @author gerbm
 */
public class Calculadora extends javax.swing.JFrame {

     
    




    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        aplicarTemaOscuro();
      

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jTFPantalla = new javax.swing.JTextField();
        jButton_Es_Igual_A = new javax.swing.JButton();
        jButton_Multiplicacion = new javax.swing.JButton();
        jButton_Suma = new javax.swing.JButton();
        jButton_Resta = new javax.swing.JButton();
        jButton_RaizCuadrada = new javax.swing.JButton();
        jButton_Division = new javax.swing.JButton();
        jButton_Numero_PI = new javax.swing.JButton();
        jButton_AC = new javax.swing.JButton();
        jButton_Factorial = new javax.swing.JButton();
        jButton_Potencia = new javax.swing.JButton();
        jButton_Positivo_Negativo = new javax.swing.JButton();
        jButton_Porcentaje = new javax.swing.JButton();
        jButton_Memoria_Numero_Anterior = new javax.swing.JButton();
        jButton_Constante_euler = new javax.swing.JButton();
        jButton_Logaritmo = new javax.swing.JButton();
        jButton_LogaritmoNeperiano = new javax.swing.JButton();
        jButton_seno = new javax.swing.JButton();
        jButton_Fraccion = new javax.swing.JButton();
        jButton_coseno = new javax.swing.JButton();
        jButton_ElevarAlCuadrado = new javax.swing.JButton();
        jButton_ElevarAlCubo = new javax.swing.JButton();
        jButton_Tangente = new javax.swing.JButton();
        jButton_ParentesisApertura = new javax.swing.JButton();
        jButton_vacio3_ComaProvisonal = new javax.swing.JButton();
        jButton_ParentesisCierre = new javax.swing.JButton();
        jButton_PruebasBorrar = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton9StateChanged(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(0, 0, 0));
        jButton0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jTFPantalla.setBackground(new java.awt.Color(51, 51, 51));
        jTFPantalla.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTFPantalla.setForeground(new java.awt.Color(255, 255, 255));
        jTFPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFPantalla.setText("0");
        jTFPantalla.setToolTipText("");
        jTFPantalla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTFPantalla.setCaretColor(new java.awt.Color(5, 35, 97));
        jTFPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTFPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPantallaActionPerformed(evt);
            }
        });

        jButton_Es_Igual_A.setBackground(new java.awt.Color(221, 144, 29));
        jButton_Es_Igual_A.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Es_Igual_A.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Es_Igual_A.setText("=");
        jButton_Es_Igual_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Es_Igual_AActionPerformed(evt);
            }
        });

        jButton_Multiplicacion.setBackground(new java.awt.Color(219, 140, 30));
        jButton_Multiplicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Multiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Multiplicacion.setText("x");
        jButton_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MultiplicacionActionPerformed(evt);
            }
        });

        jButton_Suma.setBackground(new java.awt.Color(219, 140, 30));
        jButton_Suma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Suma.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Suma.setText("+");
        jButton_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SumaActionPerformed(evt);
            }
        });

        jButton_Resta.setBackground(new java.awt.Color(219, 140, 30));
        jButton_Resta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Resta.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Resta.setText("-");
        jButton_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RestaActionPerformed(evt);
            }
        });

        jButton_RaizCuadrada.setBackground(new java.awt.Color(22, 22, 22));
        jButton_RaizCuadrada.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton_RaizCuadrada.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RaizCuadrada.setText("sqrt");
        jButton_RaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RaizCuadradaActionPerformed(evt);
            }
        });

        jButton_Division.setBackground(new java.awt.Color(219, 140, 30));
        jButton_Division.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Division.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Division.setText("/");
        jButton_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DivisionActionPerformed(evt);
            }
        });

        jButton_Numero_PI.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Numero_PI.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Numero_PI.setText("Pi");
        jButton_Numero_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Numero_PIActionPerformed(evt);
            }
        });

        jButton_AC.setBackground(new java.awt.Color(22, 22, 22));
        jButton_AC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_AC.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AC.setText("AC");
        jButton_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ACActionPerformed(evt);
            }
        });

        jButton_Factorial.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Factorial.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Factorial.setText("x!");
        jButton_Factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FactorialActionPerformed(evt);
            }
        });

        jButton_Potencia.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Potencia.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jButton_Potencia.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Potencia.setText("x^y");
        jButton_Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PotenciaActionPerformed(evt);
            }
        });

        jButton_Positivo_Negativo.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Positivo_Negativo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Positivo_Negativo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Positivo_Negativo.setText("+/-");
        jButton_Positivo_Negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Positivo_NegativoActionPerformed(evt);
            }
        });

        jButton_Porcentaje.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Porcentaje.setText("%");
        jButton_Porcentaje.setBorder(null);
        jButton_Porcentaje.setBorderPainted(false);
        jButton_Porcentaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PorcentajeActionPerformed(evt);
            }
        });

        jButton_Memoria_Numero_Anterior.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Memoria_Numero_Anterior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Memoria_Numero_Anterior.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Memoria_Numero_Anterior.setText("Ans");
        jButton_Memoria_Numero_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Memoria_Numero_AnteriorActionPerformed(evt);
            }
        });

        jButton_Constante_euler.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Constante_euler.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Constante_euler.setText("e");
        jButton_Constante_euler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Constante_eulerActionPerformed(evt);
            }
        });

        jButton_Logaritmo.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Logaritmo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Logaritmo.setText("log");
        jButton_Logaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogaritmoActionPerformed(evt);
            }
        });

        jButton_LogaritmoNeperiano.setBackground(new java.awt.Color(22, 22, 22));
        jButton_LogaritmoNeperiano.setForeground(new java.awt.Color(255, 255, 255));
        jButton_LogaritmoNeperiano.setText("ln");
        jButton_LogaritmoNeperiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogaritmoNeperianoActionPerformed(evt);
            }
        });

        jButton_seno.setBackground(new java.awt.Color(51, 51, 51));
        jButton_seno.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jButton_seno.setForeground(new java.awt.Color(255, 255, 255));
        jButton_seno.setText("sin");
        jButton_seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_senoActionPerformed(evt);
            }
        });

        jButton_Fraccion.setBackground(new java.awt.Color(22, 22, 22));
        jButton_Fraccion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Fraccion.setText("1/X");
        jButton_Fraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FraccionActionPerformed(evt);
            }
        });

        jButton_coseno.setBackground(new java.awt.Color(51, 51, 51));
        jButton_coseno.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jButton_coseno.setForeground(new java.awt.Color(255, 255, 255));
        jButton_coseno.setText("cos");
        jButton_coseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cosenoActionPerformed(evt);
            }
        });

        jButton_ElevarAlCuadrado.setBackground(new java.awt.Color(51, 51, 51));
        jButton_ElevarAlCuadrado.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jButton_ElevarAlCuadrado.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ElevarAlCuadrado.setText("x^2");
        jButton_ElevarAlCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ElevarAlCuadradoActionPerformed(evt);
            }
        });

        jButton_ElevarAlCubo.setBackground(new java.awt.Color(51, 51, 51));
        jButton_ElevarAlCubo.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jButton_ElevarAlCubo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ElevarAlCubo.setText("x^3");
        jButton_ElevarAlCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ElevarAlCuboActionPerformed(evt);
            }
        });

        jButton_Tangente.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Tangente.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jButton_Tangente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Tangente.setText("tan");
        jButton_Tangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TangenteActionPerformed(evt);
            }
        });

        jButton_ParentesisApertura.setBackground(new java.awt.Color(22, 22, 22));
        jButton_ParentesisApertura.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ParentesisApertura.setText("(");
        jButton_ParentesisApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ParentesisAperturaActionPerformed(evt);
            }
        });

        jButton_vacio3_ComaProvisonal.setBackground(new java.awt.Color(22, 22, 22));
        jButton_vacio3_ComaProvisonal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_vacio3_ComaProvisonal.setForeground(new java.awt.Color(255, 255, 255));
        jButton_vacio3_ComaProvisonal.setText(".");
        jButton_vacio3_ComaProvisonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vacio3_ComaProvisonalActionPerformed(evt);
            }
        });

        jButton_ParentesisCierre.setBackground(new java.awt.Color(22, 22, 22));
        jButton_ParentesisCierre.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ParentesisCierre.setText(")");
        jButton_ParentesisCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ParentesisCierreActionPerformed(evt);
            }
        });

        jButton_PruebasBorrar.setBackground(new java.awt.Color(216, 135, 30));
        jButton_PruebasBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_PruebasBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PruebasBorrar.setText("del");
        jButton_PruebasBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PruebasBorrarActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 159, 35));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Hist");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Tangente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_seno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(jButton_ElevarAlCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ElevarAlCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTFPantalla)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_LogaritmoNeperiano, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Memoria_Numero_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_RaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton_Logaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jButton_Constante_euler, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Numero_PI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Fraccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_vacio3_ComaProvisonal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Es_Igual_A, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_Multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_ParentesisApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ParentesisCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_coseno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_AC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jButton_Positivo_Negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_PruebasBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ElevarAlCuadrado)
                    .addComponent(jButton_ElevarAlCubo)
                    .addComponent(jButton_Tangente)
                    .addComponent(jButton_seno)
                    .addComponent(jButton_coseno)
                    .addComponent(jButton_Potencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_ParentesisApertura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Positivo_Negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_PruebasBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ParentesisCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_AC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Constante_euler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Logaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Numero_PI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Fraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_LogaritmoNeperiano, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_vacio3_ComaProvisonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_Es_Igual_A, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_Memoria_Numero_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_RaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void aplicarTemaOscuro() {
    Color fondo = new Color(60, 60, 60);
    Color colorBoton = new Color(60, 60, 60);
    Color hover = new Color(80, 80, 80);
    Color fondoOscuro = new Color(25, 25, 25);

    // Cambiar el fondo del JFrame
    getContentPane().setBackground(fondoOscuro);

    // Cambiar fondo y color del campo de texto principal
    jTFPantalla.setBackground(fondo.darker());
    jTFPantalla.setForeground(Color.WHITE);
    jTFPantalla.setCaretColor(Color.WHITE);
   
}

    
  
    
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "8";
        } else {
            pantalla = pantalla + "8";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "5";
        } else {
            pantalla = pantalla + "5";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "2";
        } else {
            pantalla = pantalla + "2";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "6";
        } else {
            pantalla = pantalla + "6";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "3";
        } else {
            pantalla = pantalla + "3";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton3ActionPerformed

    

    private ArrayList<String> historialResultado = new ArrayList<>();
    private void jButton_Es_Igual_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Es_Igual_AActionPerformed

        String pantalla = jTFPantalla.getText().trim();  // Eliminar espacios innecesarios

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$") && parentesisCorrectos(pantalla)) {
            try {
                
                 // Detectar y resolver 1/ antes de evaluar la expresión
                pantalla = resolverDivisionPorUno(pantalla);

                // Detectar y calcular factoriales antes de evaluar la expresión
                pantalla = resolverFactoriales(pantalla);

                // Convertir % a su equivalente en multiplicación con el número anterior
                String expresionLimpia = pantalla.replaceAll("(\\d+(\\.\\d*)?)%", "($1*0.01)");

                // Ajustar expresiones del tipo "X - Y%" a "X - (X * Y * 0.01)"
                expresionLimpia = expresionLimpia.replaceAll("(\\d+(\\.\\d*)?)\\s*([+\\-])\\s*(\\(\\d+(\\.\\d*)?\\*0.01\\))",
                        "($1 $3 ($1 * $4))");

                // Eliminar espacios innecesarios
                expresionLimpia = expresionLimpia.replaceAll("\\s+", "");

                // Evaluar la expresión matemática USANDO expresionLimpia
                Expression expresion = new ExpressionBuilder(expresionLimpia).build();
                double resultado = expresion.evaluate();

                numeroHistorial = resultado;
                ansGuardado = true;
                
                historialResultado.add(String.valueOf(resultado)); //HISTORIAL

                // Mostrar el resultado en la pantalla
                jTFPantalla.setText(String.valueOf(resultado));

            } catch (Exception e) {
                jTFPantalla.setText("Error");
                e.printStackTrace(); // Esto imprimirá el error en la consola, lo cual es útil para depurar
            }

        } else {
            jTFPantalla.setText("Error"); // Si hay un formato incorrecto
        }

        /*
        if (!pantalla.isEmpty() && realizandoSuma) {
            String[] numeros = pantalla.split(" \\+ "); // Separa los números en base al "+"

            if (numeros.length == 2) { // Verifica que haya dos números
                double numero1 = Double.parseDouble(numeros[0]);
                double numero2 = Double.parseDouble(numeros[1]);
                double resultado = numero1 + numero2;
                jTFPantalla.setText(String.valueOf(resultado));

                //Para almacenar automáticamente el resultado en el botón "Ans"
                numeroHistorial = Double.parseDouble(pantalla);
                ansGuardado = true;
                numeroHistorial = resultado;

                // Reiniciar variables
                numero1 = resultado; // Guardamos el resultado para futuras operaciones
                realizandoSuma = false;
            }
        }
         
        if (!pantalla.isEmpty() && realizandoMultiplicacion) {
            double numero2Multiplicacion = Double.parseDouble(pantalla);
            double resultadoMultiplicacion = numero1 * numero2Multiplicacion;
            jTFPantalla.setText(String.valueOf(resultadoMultiplicacion));

            //Para almacenar automáticamente el resultado en el botón "Ans"
            numeroHistorial = Double.parseDouble(pantalla);
            ansGuardado = true;
            numeroHistorial = resultadoMultiplicacion;

            // Reiniciar variables
            numero1 = resultadoMultiplicacion; // Guardamos el resultado para futuras operaciones
            realizandoMultiplicacion = false;
        }

        if (!pantalla.isEmpty() && realizandoResta) {
            double numero2 = Double.parseDouble(pantalla);
            double resultadoResta = numero1 - numero2;
            jTFPantalla.setText(String.valueOf(resultadoResta));

            //Para almacenar automáticamente el resultado en el botón "Ans"
            numeroHistorial = Double.parseDouble(pantalla);
            ansGuardado = true;
            numeroHistorial = resultadoResta;

            // Reiniciar variables
            numero1 = resultadoResta; // Guardamos el resultado para futuras operaciones
            realizandoResta = false;
        }

        if (!pantalla.isEmpty() && realizandoDivision) {
            double numero2 = Double.parseDouble(pantalla);
            double resultadoDivision = numero1 / numero2;
            jTFPantalla.setText(String.valueOf(resultadoDivision));

            //Para almacenar automáticamente el resultado en el botón "Ans"
            numeroHistorial = Double.parseDouble(pantalla);
            ansGuardado = true;
            numeroHistorial = resultadoDivision;

            // Reiniciar variables
            numero1 = resultadoDivision; // Guardamos el resultado para futuras operaciones
            realizandoDivision = false;
        }

        if (!pantalla.isEmpty() && realizandoPotencia) {
            double numero2 = Double.parseDouble(pantalla);
            double resultadoPotencia = Math.pow(numero1, numero2);
            jTFPantalla.setText(String.valueOf(resultadoPotencia));

            //Para almacenar automáticamente el resultado en el botón "Ans"
            numeroHistorial = Double.parseDouble(pantalla);
            ansGuardado = true;
            numeroHistorial = resultadoPotencia;

            // Reiniciar variables
            numero1 = resultadoPotencia; // Guardamos el resultado para futuras operaciones
            realizandoPotencia = false;
        }

        if (!pantalla.isEmpty() && realizandoPorcentaje) {
            double numeroActual = Double.parseDouble(pantalla);
            double resultadoPorcentaje = (numero1 * numeroActual) / 100;
            jTFPantalla.setText(String.valueOf(resultadoPorcentaje));

            //Para almacenar automáticamente el resultado en el botón "Ans"
            numeroHistorial = Double.parseDouble(pantalla);
            ansGuardado = true;
            numeroHistorial = resultadoPorcentaje;

            // Reiniciar variables
            numero1 = resultadoPorcentaje; // Guardamos el resultado para futuras operaciones
            realizandoPorcentaje = false;
        }
         */

    }//GEN-LAST:event_jButton_Es_Igual_AActionPerformed

    private boolean realizandoMultiplicacion = false;
    private void jButton_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MultiplicacionActionPerformed

        String pantalla = jTFPantalla.getText().trim();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText(pantalla + " * ");
        }

        /*
        if (!pantalla.isEmpty()) {
            if (realizandoMultiplicacion) {
                // Si ya se está realizando una multiplicación, se calcula el resultado
                double numero2Multiplicacion = Double.parseDouble(pantalla);
                double resultadoMultiplicacion = numero1 * numero2Multiplicacion;
                jTFPantalla.setText(String.valueOf(resultadoMultiplicacion));
                numero1 = resultadoMultiplicacion; // Guardamos el resultado para futuras operaciones
            } else {
                // Si no se está haciendo ninguna multiplicación, se almacena el primer número
                numero1 = Double.parseDouble(pantalla);
            }
            realizandoMultiplicacion = true; // Indica que se está realizando la multiplicación
            jTFPantalla.setText(""); // Limpia la pantalla para el siguiente número
        }
         */
    }//GEN-LAST:event_jButton_MultiplicacionActionPerformed

    private double numero1 = 0;
    private boolean realizandoSuma = false;
    private void jButton_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SumaActionPerformed

        String pantalla = jTFPantalla.getText().trim();
        
        
        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText(pantalla + " + ");
        }

        /* código antiguo
        if (!pantalla.isEmpty()) {
        jTFPantalla.setText(pantalla + " + ");
            if (realizandoSuma) {
                // Si ya se está realizando una suma, se calcula el resultado

                double numero2 = Double.parseDouble(pantalla);
                double resultado = numero1 + numero2;
                jTFPantalla.setText(resultado + " + "); // Muestra la operación en pantalla
                numero1 = resultado;
                // Guardamos el resultado para futuras operaciones
            } else {
                // Si no se está haciendo ninguna suma, se almacena el primer número
                numero1 = Double.parseDouble(pantalla);
                jTFPantalla.setText(pantalla + " + ");  // Mantiene el número y agrega el "+"
            }
            realizandoSuma = true; // Indica que se está realizando la suma

        }
         */

    }//GEN-LAST:event_jButton_SumaActionPerformed

    private boolean realizandoResta = false;
    private void jButton_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RestaActionPerformed

        String pantalla = jTFPantalla.getText().trim();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText(pantalla + " - ");
        }

        /*
        if (!pantalla.isEmpty()) {
            if (realizandoResta) {
                // Si ya se está realizando una resta, se calcula el resultado
                double numero2 = Double.parseDouble(pantalla);
                double resultadoResta = numero1 - numero2;
                jTFPantalla.setText(String.valueOf(resultadoResta));
                numero1 = resultadoResta; // Guardamos el resultado para futuras operaciones
            } else {
                // Si no se está haciendo ninguna resta, se almacena el primer número
                numero1 = Double.parseDouble(pantalla);
            }
            realizandoResta = true; // Indica que se está realizando la resta
            jTFPantalla.setText(""); // Limpia la pantalla para el siguiente número
        }
         */
    }//GEN-LAST:event_jButton_RestaActionPerformed

    private void jButton_RaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RaizCuadradaActionPerformed
        String pantalla = jTFPantalla.getText();

        // Si la pantalla es igual a 0 o termina en un operador, añadimos "sqrt("
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("sqrt(");
        } else {
            // Si hay un número en pantalla, interpretamos que quiere hacer sqrt(número)
            try {
                double numero = Double.parseDouble(pantalla);
                double resultado = Math.sqrt(numero);

                // Formatear resultado con 5 decimales
                // String resultadoFormateado = String.format(Locale.US, "%.5f", resultado);
                jTFPantalla.setText(resultado + "");

            } catch (NumberFormatException e) {
                // Si hay un error, solo insertar "sqrt(" sin evaluar
                jTFPantalla.setText(pantalla + "*sqrt(");
            }

        }

        /*
        Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.sqrt(numero);
        pantalla = operacion.toString();

        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;

         */
    }//GEN-LAST:event_jButton_RaizCuadradaActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "9";
        } else {
            pantalla = pantalla + "9";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTFPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPantallaActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (!(pantalla.length() == 1 && pantalla.contains("0"))) {
            pantalla = pantalla + "0";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton0ActionPerformed

    private boolean realizandoDivision;
    private void jButton_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DivisionActionPerformed

        String pantalla = jTFPantalla.getText().trim();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText(pantalla + " / ");
        }

        /*
        if (!pantalla.isEmpty()) {
            try {
                if (realizandoDivision) {
                    // Si ya se está realizando una suma, se calcula el resultado
                    double numero2 = Double.parseDouble(pantalla);
                    if (numero2 == 0) {
                        throw new DividirPorCeroException("infinito.");
                    }
                    double resultadoDivision = numero1 / numero2;
                    jTFPantalla.setText(String.valueOf(resultadoDivision));
                    numero1 = resultadoDivision;  // Guardamos el resultado para futuras operaciones
                } else {
                    numero1 = Double.parseDouble(pantalla);
                }
                realizandoDivision = true; // Indica que se está realizando la suma
                jTFPantalla.setText(""); // Limpia la pantalla para el siguiente número
            } catch (DividirPorCeroException e) {
                jTFPantalla.setText(e.getMessage());

                realizandoDivision = false;
            }
        }
         */

    }//GEN-LAST:event_jButton_DivisionActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "1";
        } else {
            pantalla = pantalla + "1";
        }

        jTFPantalla.setText(pantalla);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "4";
        } else {
            pantalla = pantalla + "4";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String pantalla = jTFPantalla.getText();
        if (pantalla.length() == 1 && pantalla.contains("0")) {
            pantalla = "7";
        } else {
            pantalla = pantalla + "7";
        }

        jTFPantalla.setText(pantalla);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton_Numero_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Numero_PIActionPerformed
        String pantalla = jTFPantalla.getText();

        // Si la pantalla está vacía o termina en un operador, añadimos "?"
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("3.141592");
        } else {
            try {
                double numero = Double.parseDouble(pantalla.replace(",", ".")); // Asegurar formato numérico
                double resultado = numero * 3.141592;

                // Formatear el resultado con punto decimal
                String resultadoFormateado = String.format(Locale.US, "%.4f", resultado);

                jTFPantalla.setText(resultadoFormateado);
                numeroHistorial = resultado; // Guardar en historial correctamente

            } catch (NumberFormatException e) {
                jTFPantalla.setText(pantalla + "3.141592");
            }
        }

        ansGuardado = true;


    }//GEN-LAST:event_jButton_Numero_PIActionPerformed

    private void jButton_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ACActionPerformed
        String pantalla = jTFPantalla.getText();

        if (!pantalla.isEmpty()) {
            jTFPantalla.setText("0");
            realizandoSuma = false;
            realizandoResta = false;
            realizandoDivision = false;
            realizandoMultiplicacion = false;
            realizandoPotencia = false;
            realizandoPorcentaje = false;

            numero1 = 0;
        }
        // Opcional: dar foco al campo de texto
        jTFPantalla.requestFocus();


    }//GEN-LAST:event_jButton_ACActionPerformed


    private void jButton_FactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FactorialActionPerformed

        String pantalla = jTFPantalla.getText();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText(pantalla + "!");
        }
        /*
        double numero = Double.parseDouble(pantalla);
        
        int numero1 = (int) numero; //Convierto en número double a un tipo int par asarlo de extremo en el array

        int[] numeros = new int[numero1]; //Creo un array con la longitud que el usuairo introduzca, si introduce un "5", pues será de 5

        //Lleno el array de valores decrecientes hata 1 
        for (int i = 0; i < numero1; i++) {
            numeros[i] = numero1 - i;
        }

        int operacion = 1; //Acumulador
        for (int i = 0; i < numeros.length; i++) {
            operacion *= numeros[i]; //Los multiplico y los sumo
        }

        pantalla = String.valueOf(operacion); //Convierto el resultado a un String para manejar la salida
        jTFPantalla.setText(pantalla);
         

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        //  numeroHistorial = operacion;
         */

    }//GEN-LAST:event_jButton_FactorialActionPerformed

//___________________________________________________________________________________________________________________
    private String resolverFactoriales(String expresion) {
        // Expresión regular para encontrar números seguidos de "!"
        Pattern pattern = Pattern.compile("(\\d+)!"); // (\\d+) ? Captura un número (uno o más dígitos || ! ? Indica que debe ir seguido de un signo de factorial (!).
        Matcher matcher = pattern.matcher(expresion); //    Matcher matcher = pattern.matcher(expresion);

        StringBuffer nuevaExpresion = new StringBuffer(); // StringBuffer se usa para construir la nueva expresión a medida que se reemplazan los factoriales.
        //Es más eficiente que concatenar Strings con +, ya que modifica el texto sin crear nuevos objetos.

        while (matcher.find()) {
            int numero = Integer.parseInt(matcher.group(1)); // Extraer el número antes del "!"
            long resultadoFactorial = factorial(numero); // Calcular factorial
            matcher.appendReplacement(nuevaExpresion, String.valueOf(resultadoFactorial)); // Reemplazar en la expresión
        }

        /*
    - matcher.find() ? Busca la siguiente ocurrencia del patrón en la expresión.
    - matcher.group(1) ? Obtiene el número antes del !.
    
    Si expresion = "5! + 3!", la primera coincidencia es "5!", por lo que matcher.group(1) devuelve "5".
    - Integer.parseInt(matcher.group(1)) ? Convierte ese número a int.
    - factorial(numero) ? Llama a una función (que debes haber definido antes) para calcular el factorial.
    - matcher.appendReplacement(nuevaExpresion, String.valueOf(resultadoFactorial))
    
    Reemplaza el número factorial en la nueva expresión.
    "5!" se convierte en "120".
    "5! + 3!" se convertirá en "120 + 6".
         */
        matcher.appendTail(nuevaExpresion);

        /*
    Esto añade el resto de la cadena que no fue procesada.
    
    Si la expresión era "5! + 3! - 2", el while reemplazó "5!" y "3!", pero "- 2" sigue intacto.
    - appendTail agrega " - 2" al final de nuevaExpresion.
         */
        return nuevaExpresion.toString();
        /*
    Devolver la Nueva Expresión con los Factoriales Resueltos
    -  return nuevaExpresion.toString();
    
    Ejemplo de entrada: "4! + 2!"
    Salida esperada: "24 + 2"
         */
    }

    private long factorial(int n) {
        if (n < 0) {
            return 1; // Manejo de error para valores negativos (puedes lanzar una excepción si prefieres)
        }
        long resultado = 1;
        for (int i = 1; i <= n; i++) {
            resultado *= i;
        }
        return resultado;
    }

    //___________________________________________________________________________________________________________________
    private boolean realizandoPotencia;
    private void jButton_PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PotenciaActionPerformed
        String pantalla = jTFPantalla.getText().trim();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText(pantalla + " ^ ");
        }

        /*  
        if (!pantalla.isEmpty()) {
            if (realizandoPotencia) {
                // Si ya se está realizando una resta, se calcula el resultado
                double numero2 = Double.parseDouble(pantalla);
                double resultadoPotencia = Math.pow(numero1, numero2);
                jTFPantalla.setText(String.valueOf(resultadoPotencia));
                numero1 = resultadoPotencia; // Guardamos el resultado para futuras operaciones
            } else {
                // Si no se está haciendo ninguna resta, se almacena el primer número
                numero1 = Double.parseDouble(pantalla);
            }
            realizandoPotencia = true; // Indica que se está realizando la resta
            jTFPantalla.setText(""); // Limpia la pantalla para el siguiente número
        }
         */

    }//GEN-LAST:event_jButton_PotenciaActionPerformed

    private void jButton_Positivo_NegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Positivo_NegativoActionPerformed
        String pantalla = jTFPantalla.getText();
        Double numero1 = Double.parseDouble(pantalla);

        Double operacion = numero1 * -1;

        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

    }//GEN-LAST:event_jButton_Positivo_NegativoActionPerformed

    /*private double numeroPorcentaje;
    private boolean realizandoPorcentaje = false;
     */
    private boolean realizandoPorcentaje = false;
    private void jButton_PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PorcentajeActionPerformed

        String pantalla = jTFPantalla.getText();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText(pantalla + "%");
        }

        /*
        if (!pantalla.isEmpty()) {
            double numeroActual = Double.parseDouble(pantalla);

            if (realizandoPorcentaje) {
                // Si ya se está realizando un porcentaje, se calcula el resultado
                double resultadoPorcentaje = (numero1 * numeroActual) / 100;
                jTFPantalla.setText(String.valueOf(resultadoPorcentaje));
                numero1 = resultadoPorcentaje; // Actualiza para futuras operaciones
            } else {
                numero1 = Double.parseDouble(pantalla);
            }
            realizandoPorcentaje = true;// Indica que se está realizando el porcentaje
            jTFPantalla.setText(""); // Limpia la pantalla para el siguiente número
        }
         */

    }//GEN-LAST:event_jButton_PorcentajeActionPerformed

    private double numeroHistorial = 0;
    private boolean ansGuardado = false; //es para  saber si hay un valor  guardado
    private void jButton_Memoria_Numero_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Memoria_Numero_AnteriorActionPerformed
        String pantalla = jTFPantalla.getText();
        jTFPantalla.setText(""); // Limpia la pantalla para el siguiente número

        if (!ansGuardado) {
            // Si no hay un valor ANS guardado, guardamos el valor actual
            if (!pantalla.isEmpty() && !pantalla.equals("0")) {
                numeroHistorial = Double.parseDouble(pantalla);
                ansGuardado = true;
                jTFPantalla.setText("Ans: " + numeroHistorial);
            }
        } else {
            // Si ya hay un valor ANS guardado, lo recuperamos
            jTFPantalla.setText(String.valueOf(numeroHistorial));
            ansGuardado = false; // Reseteamos el flag para el próximo uso
        }


    }//GEN-LAST:event_jButton_Memoria_Numero_AnteriorActionPerformed

    private void jButton_Constante_eulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Constante_eulerActionPerformed

        String pantalla = jTFPantalla.getText();

        // Si la pantalla está vacía o termina en un operador, añadimos "?"
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("2.7182818");
        } else {
            try {
                double numero = Double.parseDouble(pantalla.replace(",", ".")); // Asegurar formato numérico
                double resultado = numero * 2.7182818;

                // Formatear el resultado con punto decimal
                String resultadoFormateado = String.format(Locale.US, "%.4f", resultado);

                jTFPantalla.setText(resultadoFormateado);
                numeroHistorial = resultado; // Guardar en historial correctamente

            } catch (NumberFormatException e) {
                jTFPantalla.setText(pantalla + "2.7182818");
            }
        }

        ansGuardado = true;

        /*
        double numero;

        if (!pantalla.isEmpty() && !pantalla.equals("0")) {
            try {
                numero = Double.parseDouble(pantalla);
                double resultado = numero * 2.7182818284; // Usamos la variable e

                // Formateamos el resultado para mostrar solo 4 decimales
                String resultado_e = String.format("%.5f", resultado);
                jTFPantalla.setText(resultado_e);

            } catch (NumberFormatException e) {
                jTFPantalla.setText("Error");

            }
        } else {
            // Si la pantalla está vacía, simplemente mostramos el valor de pi
            jTFPantalla.setText("2.71828182846");
        }

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = 2.71828182846;
         */
    }//GEN-LAST:event_jButton_Constante_eulerActionPerformed

    private void jButton_LogaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogaritmoActionPerformed
        String pantalla = jTFPantalla.getText();

        // Si la pantalla es igual a 0 o termina en un operador, añadimos "log("
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("log10(");
        } else {
            // Si hay un número en pantalla, interpretamos que quiere hacer sqrt(número)
            try {
                double numero = Double.parseDouble(pantalla);
                double resultado = Math.log10(numero);

                // Formatear resultado con 5 decimales
                // String resultadoFormateado = String.format(Locale.US, "%.5f", resultado);
                jTFPantalla.setText(resultado + "");

            } catch (NumberFormatException e) {
                // Si hay un error, solo insertar "sqrt(" sin evaluar
                jTFPantalla.setText(pantalla + "*log10(");
            }

        }

        /*Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.log10(numero);
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
         */
    }//GEN-LAST:event_jButton_LogaritmoActionPerformed

    private void jButton_LogaritmoNeperianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogaritmoNeperianoActionPerformed
        String pantalla = jTFPantalla.getText();

        // Si la pantalla es igual a 0 o termina en un operador, añadimos "ln("
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("log(");
        } else {
            // Si hay un número en pantalla, interpretamos que quiere hacer sqrt(número)
            try {
                double numero = Double.parseDouble(pantalla);
                double resultado = Math.log(numero);

                // Formatear resultado con 5 decimales
                // String resultadoFormateado = String.format(Locale.US, "%.5f", resultado);
                jTFPantalla.setText(resultado + "");

            } catch (NumberFormatException e) {
                // Si hay un error, solo insertar "sqrt(" sin evaluar
                jTFPantalla.setText(pantalla + "*log(");
            }

        }
        
        

        /*
        Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.log(numero);
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
         */
    }//GEN-LAST:event_jButton_LogaritmoNeperianoActionPerformed

    private void jButton_senoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_senoActionPerformed
        String pantalla = jTFPantalla.getText();

        // Si la pantalla es igual a 0 o termina en un operador, añadimos "sin("
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("sin(");
        } else {
            // Si hay un número en pantalla, interpretamos que quiere hacer sqrt(número)
            try {
                double numero = Double.parseDouble(pantalla);
                double resultado = Math.sin(numero);

                // Formatear resultado con 5 decimales
                // String resultadoFormateado = String.format(Locale.US, "%.5f", resultado);
                jTFPantalla.setText(resultado + "");

            } catch (NumberFormatException e) {
                // Si hay un error, solo insertar "sqrt(" sin evaluar
                jTFPantalla.setText(pantalla + "*sin(");
            }

        }

        /*
        Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.sin(numero);
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
         */
    }//GEN-LAST:event_jButton_senoActionPerformed

    
    //__________________________________________________________________________________________________________________
    
    private void jButton_FraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FraccionActionPerformed
        String pantalla = jTFPantalla.getText();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("1/" + pantalla);
        }
        
        if(pantalla.equals("0")){
             jTFPantalla.setText("1/");
        }

        /*
        Double numero = Double.parseDouble(pantalla);

        Double operacion = 1 / numero;
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
         */

    }//GEN-LAST:event_jButton_FraccionActionPerformed

    private String resolverDivisionPorUno(String expresion) {
        // Expresión regular para encontrar números antececidos de "1/"
        Pattern pattern = Pattern.compile("1/(\\d+)!");
        Matcher matcher = pattern.matcher(expresion);

        StringBuffer nuevaDivision = new StringBuffer();

        while (matcher.find()) {
            int numero = Integer.parseInt(matcher.group(1)); // Extraer el número de desues de 1/
            double resultadoDivision = divisionPorUno(numero); // Calcular factorial
            matcher.appendReplacement(nuevaDivision, String.valueOf(resultadoDivision)); // Reemplazar en la expresión
        }

        matcher.appendTail(nuevaDivision);
        return nuevaDivision.toString();
    }

    private double divisionPorUno(int numero) {
        return 1.0 / numero; //Para evitar problemas con los enteros
    }
    
     //__________________________________________________________________________________________________________________


    private void jButton_cosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cosenoActionPerformed
        String pantalla = jTFPantalla.getText();

        // Si la pantalla es igual a 0 o termina en un operador, añadimos "cos("
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("cos(");
        } else {
            // Si hay un número en pantalla, interpretamos que quiere hacer sqrt(número)
            try {
                double numero = Double.parseDouble(pantalla);
                double resultado = Math.cos(numero);

                // Formatear resultado con 5 decimales
                // String resultadoFormateado = String.format(Locale.US, "%.5f", resultado);
                jTFPantalla.setText(resultado + "");

            } catch (NumberFormatException e) {
                // Si hay un error, solo insertar "sqrt(" sin evaluar
                jTFPantalla.setText(pantalla + "*cos(");
            }

        }

        /*
        Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.cos(numero);
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
         */
    }//GEN-LAST:event_jButton_cosenoActionPerformed

    private void jButton_ElevarAlCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ElevarAlCuadradoActionPerformed
        String pantalla = jTFPantalla.getText();
        Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.pow(numero, 2);
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
    }//GEN-LAST:event_jButton_ElevarAlCuadradoActionPerformed

    private void jButton_ElevarAlCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ElevarAlCuboActionPerformed
        String pantalla = jTFPantalla.getText();
        Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.pow(numero, 3);
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
    }//GEN-LAST:event_jButton_ElevarAlCuboActionPerformed

    //____________________________Revisar este código y entenderlo 
    private void jButton_TangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TangenteActionPerformed
        String pantalla = jTFPantalla.getText();

        // Si la pantalla es igual a 0 o termina en un operador, añadimos "tan("
        if (pantalla.equals("0") || pantalla.matches(".*[+\\-*/]$")) {
            jTFPantalla.setText("tan(");
        } else {
            // Si hay un número en pantalla, interpretamos que quiere hacer sqrt(número)
            try {
                double numero = Double.parseDouble(pantalla);
                double resultado = Math.tan(numero);

                // Formatear resultado con 5 decimales
                // String resultadoFormateado = String.format(Locale.US, "%.5f", resultado);
                jTFPantalla.setText(resultado + "");

            } catch (NumberFormatException e) {
                // Si hay un error, solo insertar "sqrt(" sin evaluar
                jTFPantalla.setText(pantalla + "*tan(");
            }

        }

        /*
        Double numero = Double.parseDouble(pantalla);

        Double operacion = Math.tan(numero);
        pantalla = operacion.toString();
        jTFPantalla.setText(pantalla);

        numeroHistorial = Double.parseDouble(pantalla);
        ansGuardado = true;
        numeroHistorial = operacion;
         */
    }//GEN-LAST:event_jButton_TangenteActionPerformed

    private void jButton_ParentesisAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ParentesisAperturaActionPerformed

        String pantalla = jTFPantalla.getText();
        if (pantalla.equals("0")) {
            jTFPantalla.setText("(");
        } else {
            jTFPantalla.setText(pantalla + "(");
        }
    }//GEN-LAST:event_jButton_ParentesisAperturaActionPerformed

    private boolean parentesisCorrectos(String comprobador) {
        int contador = 0;
        for (char c : comprobador.toCharArray()) {
            if (c == '(') {
                contador++;
            } else if (c == ')') {
                contador--;
                if (contador != 0) {
                    return false; //No coinciden el número de paréntesis
                }
            }
        }
        return contador == 0; // Debe haber la misma cantidad de "(" y ")"
    }

    //_____________________________________________________________________________________________________________

    private void jButton_vacio3_ComaProvisonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vacio3_ComaProvisonalActionPerformed
        String pantalla = jTFPantalla.getText();
        
        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$") && !pantalla.contains(".")) {
            jTFPantalla.setText(pantalla + ".");
        }
        
    }//GEN-LAST:event_jButton_vacio3_ComaProvisonalActionPerformed

    private void jButton_ParentesisCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ParentesisCierreActionPerformed
        jTFPantalla.setText(jTFPantalla.getText() + ")");
    }//GEN-LAST:event_jButton_ParentesisCierreActionPerformed

    private void jButton_PruebasBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PruebasBorrarActionPerformed
        String pantalla = jTFPantalla.getText();

        if (!pantalla.isEmpty() && !pantalla.matches(".*[+\\-*/]$")) {
            //Borrar el último dígito, haciendo de los números de la pantalla una cadena
            pantalla = pantalla.substring(0, pantalla.length() - 1);

            //Si la pantalla está vaacía o es = a 0, se pone que muestre un 0 para evitar que se quede vacía
            if (pantalla.equals("0") || pantalla.isEmpty()) {
                pantalla = "0";
            }

            jTFPantalla.setText(pantalla);
        }
    }//GEN-LAST:event_jButton_PruebasBorrarActionPerformed

    private void jButton9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton9StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9StateChanged

    private void jButtonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistorialActionPerformed
       String historialComoTexto = String.join("\n | ", historialResultado);
        
        jTFPantalla.setText(historialComoTexto); 
    }//GEN-LAST:event_jButtonHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
    /* Set the Nimbus look and feel - debe ir ANTES de crear la ventana */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    /* Crear y mostrar la ventana DESPUÉS de aplicar el Look and Feel */
    java.awt.EventQueue.invokeLater(() -> {
        new Calculadora().setVisible(true);
    });
}
 
          
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_AC;
    private javax.swing.JButton jButton_Constante_euler;
    private javax.swing.JButton jButton_Division;
    private javax.swing.JButton jButton_ElevarAlCuadrado;
    private javax.swing.JButton jButton_ElevarAlCubo;
    private javax.swing.JButton jButton_Es_Igual_A;
    private javax.swing.JButton jButton_Factorial;
    private javax.swing.JButton jButton_Fraccion;
    private javax.swing.JButton jButton_Logaritmo;
    private javax.swing.JButton jButton_LogaritmoNeperiano;
    private javax.swing.JButton jButton_Memoria_Numero_Anterior;
    private javax.swing.JButton jButton_Multiplicacion;
    private javax.swing.JButton jButton_Numero_PI;
    private javax.swing.JButton jButton_ParentesisApertura;
    private javax.swing.JButton jButton_ParentesisCierre;
    private javax.swing.JButton jButton_Porcentaje;
    private javax.swing.JButton jButton_Positivo_Negativo;
    private javax.swing.JButton jButton_Potencia;
    private javax.swing.JButton jButton_PruebasBorrar;
    private javax.swing.JButton jButton_RaizCuadrada;
    private javax.swing.JButton jButton_Resta;
    private javax.swing.JButton jButton_Suma;
    private javax.swing.JButton jButton_Tangente;
    private javax.swing.JButton jButton_coseno;
    private javax.swing.JButton jButton_seno;
    private javax.swing.JButton jButton_vacio3_ComaProvisonal;
    private javax.swing.JTextField jTFPantalla;
    // End of variables declaration//GEN-END:variables
}
